name: dependabot-build
on:
  push:
    branches: main
  pull_request:
    branches: main

permissions: {}

jobs:
  dependabot-build:
    permissions:
      contents: read
    if: |
      github.actor == 'dependabot[bot]'
    uses: ./.github/workflows/docker-build-image.yml
    with:
      registry_push: false

  dependabot-merge:
    needs:
      - dependabot-build
    permissions:
      contents: write
      pull-requests: write
    if: |
      success() && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Find associated PR
        uses: jwalton/gh-find-current-pr@f3d61b485d2801773f7a07b2aaa3306bd8f8e653 # v1.3.5
        id: findpr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          state: open
          sha: ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}
      - name: merge-if-built
        continue-on-error: true
        uses: fastify/github-action-merge-dependabot@30c3f8f14a4f7b315ba38dbc1b793d27128fef82 # v3.12.0
        with:
          pr-number: ${{ steps.findpr.outputs.pr }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          target: minor
