name: dependabot-build
on:
  push:
    branches: main
  pull_request:
    branches: main

permissions: {}

jobs:
  dependabot-build:
    permissions:
      contents: read
    if: |
      github.actor == 'dependabot[bot]'
    uses: ./.github/workflows/docker-build-image.yml
    with:
      registry_push: false

  dependabot-merge:
    needs:
      - dependabot-build
    permissions:
      contents: write
      pull-requests: write
    if: |
      success() && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Find associated PR
        uses: jwalton/gh-find-current-pr@89ee5799558265a1e0e31fab792ebb4ee91c016b # v1.3.3
        id: findpr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          state: open
          sha: ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}
      - name: merge-if-built
        continue-on-error: true
        uses: fastify/github-action-merge-dependabot@9e7bfb249c69139d7bdcd8d984f9665edd49020b # v3.10.1
        with:
          pr-number: ${{ steps.findpr.outputs.pr }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          target: minor
