name: docker-build-latest

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/docker-hub-desc.yml"

permissions: {}

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build-image.yml
    with:
      registry_push: true
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKER_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}
