name: docker-build-tag

on:
  push:
    tags:
      - '*'

jobs:
  docker-tag:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/docker-build-image.yml
    with:
      registry_push: true