name: docker-build-tag

on:
  push:
    tags:
      - '*'

permissions: {}

jobs:
  docker-tag:
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build-image.yml
    with:
      registry_push: true