name: docker-build-latest

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/docker-hub-desc.yml"

permissions: {}

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build-image.yml
    with:
      registry_push: true
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKER_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  nginx-wpad-published:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: dispatch
        uses: quotidian-ennui/actions-olio/pr-trigger@607bdc8b9da4a24dbfb6aea4160f5cf5e205f2b2 # v1.3.6
        with:
          event_type: "nginx-wpad-published"
