name: docker-build-latest

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

permissions: {}

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build-image.yml
    with:
      registry_push: true
